import { Inter } from "next/font/google";

import { Navbar } from "@/components/navbar";

import { cn } from "@/lib/utils";

import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saas platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <Providers>
        <body
          className={cn(
            "min-h-screen font-sans antialiased grayscale",
            inter.className
          )}>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
